services:
  - type: web
    name: beyondwords-python-api
    env: python
    plan: starter
    buildCommand: |
      apt-get update && 
      apt-get install -y espeak espeak-data && 
      pip install -r requirements.txt
    startCommand: python python_api.py
    envVars:
      - key: PORT
        value: 5000
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false